name: Build Integration

on:
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo "Add Tests ASAP...."

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          cache: pip
      - uses: pre-commit/action@v2.0.3
